topology/encryption.go
topology/encryption_test.go
topology/topology.go

Encode aes encrypted data to hex to match format on online calculator.

chore: Encode aes encrypted data to hex

---

go.mod
go.sum

fix: bump core version

---

ecs/task_definition-0_STAGE.json
ecs/task_definition-1_STAGE.json
ecs/task_definition-2_STAGE.json
ecs/task_definition-3_STAGE.json
ecs/task_definition-4_STAGE.json

Add moonbase network to aws task definitions.

chore: add moonbase to task definitions

---

cli/cli.go
cli/peer/cli.go
cli/peer/generateKey.go
cli/peer/info.go

Implement generate libp2p key command to make generating key for partners more straight forward.
Refactor peer-info command to be under the peer command umbrella.
Closes: #32

feat: Generate libp2p key command

---

.github/workflows/pr.yml
.github/workflows/publish-binaries.yml
.github/workflows/release.yml
Makefile

This PR adds:
- publishing of binaries on release
- validating PR titles so it matches semver
Closes: #29

chore: publish binaries on release

---

.github/workflows/code-quality.yml
.github/workflows/dependecy-review.yml

Found out that github added a native code quality analysis tool.
Will add to the repo so how it works. Notifications should arrive on PRs and security tab apparently.

chore: add code quality analysis by github

---

chains/substrate/chain.go
chains/substrate/config.go
chains/substrate/config_test.go
config/substrate.go

Add substrate config parser function +  tests
Closes: #24 
unit tests

feat: Add substrate chain type

---

config/config_test.go
config/env.go
config/env_test.go
config/relayer/config.go
ecs/task_definition-0_STAGE.json
ecs/task_definition-1_STAGE.json
ecs/task_definition-2_STAGE.json
ecs/task_definition-3_STAGE.json
ecs/task_definition-4_STAGE.json
example/cfg/config_evm-evm_1.json
example/cfg/config_evm-evm_2.json
example/cfg/config_evm-evm_3.json
go.mod
go.sum
topology/topology.go

Fetch topology from http (IPFS) to avoid dependecy on storage and many variables that it needs.
Closes: #31

feat: fetch topology from ipfs

---

chains/evm/calls/contracts/bridge/bridge.go
chains/evm/listener/deposit-handler.go

Remove unused functions and extra print in deposit handler
Closes: #43 
Closes: #61

chore: remove unused functions

---

chains/evm/executor/executor.go
ecs/task_definition-0_STAGE.json
ecs/task_definition-1_STAGE.json
ecs/task_definition-2_STAGE.json
ecs/task_definition-3_STAGE.json
ecs/task_definition-4_STAGE.json

Add shibuya task definition files

chore: add shibuya to relayers

---

chains/evm/chain.go
chains/evm/executor/executor.go
chains/evm/listener/event-handler.go
comm/elector/bully.go
tss/coordinator.go

Improve logging across TSS process.

fix: improve tss process sessionID logging

---

.github/workflows/deploy_stage.yml
.github/workflows/deploy_testnet.yml

"chore: 'fixed typo on matrix job' remove duplicates & exposed data"

chore: 'fixed typo on matrix job' remove duplicates & exposed data

---

.github/workflows/deploy_stage.yml
.github/workflows/deploy_testnet.yml

chore: 'changed actor to repository_owner' remove duplicates & exposed data
forbidden error to publish the docker image to ghcr.io
forbidden error to publish
change actor to repository_owner

chore: fix repository owner

---

.github/workflows/deploy_stage.yml
.github/workflows/deploy_testnet.yml

chore: changed github_token

---

app/app.go

Add some more basic logs on the relayer startup to track progress on some of the initial steps of starting the relayer.
Related to: #85

chore: expand logging on relayer start

---

.github/workflows/deploy_stage.yml
.github/workflows/deploy_testnet.yml

This PR integrates datadog with TESTNET relayers

feat: integrate datadog in testnet relayers

---

app/app.go

chore: add explicit error log to lvlDB connection

---

.github/workflows/deploy_stage.yml

Jinja2 Render
Upgraded pipeline to use jinja2 to render json task definitions

chore: added jinja2 render

---

.github/workflows/deploy_stage.yml

Fix reference error 
reference to jinja2 template

chore: fix ref error

---

app/app.go
example/app/app.go
health/health.go

chore: execute health check when health endpoint called

---

.github/workflows/pr.yml
app/app.go

As health endpoint initialization was moved after blockstore file connection (that waits until the old instance unlocks blockstore file), the health endpoint wasn't starting properly.

fix: health endpoint not starting

---

app/app.go
chains/substrate/calls/pallets/bridge/bridge.go
chains/substrate/client/client.go
chains/substrate/connection/connection.go
chains/substrate/executor/executor.go
e2e/substrate/substrate_test.go
example/app/app.go
go.sum

chore: refactor client to use existing connection

---

chains/substrate/events/events.go
example/docker-compose.yml

chore: fixate versions in local setup

---

.github/workflows/deploy_stage.yml
.github/workflows/deploy_testnet.yml

Tags Versions
Added Tags Versions
Closes: #121 
Tested. Tagged branch name
- [ x] Bug fix (non-breaking change which fixes an issue)

chore: Tags Versioning

---

.github/workflows/deploy_testnet.yml

chore: fix testnet release pipeline

---

README.md
config/config.go
config/config_test.go
config/env.go
config/env_test.go

unify SYG_DOM variables into a single SYG_CHAINS variable. 
Needs updates to the task files and configurations on AWS.
Closes: #130

feat: unify SYG_DOM variables into a single SYG_CHAINS variable

---

app/app.go
comm/p2p/host.go

chore: add more debug logs for libp2p initialisation

---

app/app.go
topology/store.go
topology/store_test.go

fix: fixing Topology file fetcher and related unit test

---

comm/p2p/host_test.go

chore: fix flaky test

---

app/app.go
example/app/app.go

fix: fix latest and fresh flags being switched

---

chains/substrate/executor/message-handler.go
chains/substrate/executor/message-handler_test.go
chains/substrate/listener/deposit-handler.go
chains/substrate/listener/deposit-handler_test.go
e2e/substrate/substrate_test.go
e2e/substrate/util.go

Remove hardcoded multilocation
Remove hardcoded multilocation
Update tests accordingly
Closes: #144 
unit/e2e tests

fix: Remove hardcoded multilocation

---

app/app.go
chains/evm/chain.go
chains/substrate/chain.go
docs/general/Metrics.md
example/app/app.go
example/cfg/config_evm-evm_1.json
example/cfg/config_evm-evm_2.json
example/cfg/config_evm-evm_3.json
example/cfg/otel-collector-config.yml
example/docker-compose.yml
go.mod
go.sum
jobs/jobs.go
metrics/metrics.go
metrics/opentelemetry.go

Implement metrics for deposit count, execution count, execution latency and subset count of relayers.
Closes: #147

feat: implement metrics

---

chains/substrate/client/client.go
chains/substrate/events/events.go
chains/substrate/executor/executor.go
chains/substrate/listener/event-handlers.go
chains/substrate/pallet/pallet.go
chains/substrate/util.go
docs/general/Metrics.md
e2e/substrate/substrate_test.go
tss/signing/signing.go

Track substrate extrinsic status so we now when it is finalized and if it successed or failed.
Closes: #155 
Closes: #154

feat: track substrate extrinsic status

---

app/app.go
config/config.go
config/config_test.go
config/env.go
config/env_test.go
config/relayer/config.go
example/app/app.go
metrics/metrics.go
metrics/opentelemetry.go

ENV and RELAYER_ID env params containing current instance environment and RelayerID correspondingly, these variables are needed to distinguish metric names from each other

feat: add relayerID and instance env to configuration to use in metrics

---

app/app.go
chains/evm/listener/deposit-handler.go
chains/evm/listener/deposit-handler_test.go
chains/substrate/config.go
chains/substrate/config_test.go
chains/substrate/listener/event-handlers.go
chains/substrate/listener/event-handlers_test.go
chains/substrate/listener/listener.go
chains/substrate/listener/mock/listener.go
example/app/app.go

Use finalized head when indexing substrate instead of relying on block confirmations.
Closes: #156 
Closes: #149

feat: use finalized head when indexing substrate

---

comm/health.go
comm/p2p/libp2p.go
jobs/jobs.go

In order to better debug current KeyRefresh problem we I have update some of the logs verbosity.
Related: https://github.com/sygmaprotocol/project-backlog/issues/149

chore: add more verbosity to some p2p comm logs

---

Dockerfile
example/Dockerfile
go.mod
go.sum
metrics/metrics.go

Weird error occurs with strech-slim (missing GLIBC:2.32 and GLIBC:2.34) which is usually an OS error so bumped debian to stable version.

chore: fix glib error in docker

---

app/app.go
chains/substrate/events/events.go
chains/substrate/listener/event-handlers.go
chains/substrate/listener/event-handlers_test.go

Update metadata on app start and council executed event instead of code updated.

fix: substrate metadata update event not caught

---

.github/workflows/deploy_testnet.yml

revert testnet pipeline to previous state
Related: #208 https://github.com/sygmaprotocol/devops/issues/193#issue-1831372680

chore: revert changes to 1980918

---

.github/workflows/deploy_testnet.yml

fix: fixed efs id 

---

.github/workflows/deploy_mainnet.yml
.github/workflows/deploy_stage.yml

chore: added efs interpolation

---

.github/workflows/deploy_stage.yml

chore: fix typo

---

.github/workflows/deploy_stage.yml

Deploy relayers to multi region
Related:#194
[Test Success](https://github.com/sygmaprotocol/sygma-relayer/actions/runs/6341256031)

chore: multi region deployment

---

.github/workflows/deploy_mainnet.yml

Enable Region_1 pipeline after a successful deployment and testing of region_3
Close #194 
[Test Success](https://github.com/sygmaprotocol/sygma-relayer/actions/runs/6467624772/job/17558040996)

chore: enabled region_1 pipeline

---

chains/evm/listener/eventHandlers/event-handler.go

fix: avoid blocking when refresh and keygen fail

---

chains/evm/executor/executor.go
chains/evm/listener/eventHandlers/event-handler.go
chains/evm/listener/eventHandlers/event-handler_test.go
chains/substrate/listener/event-handlers.go
chains/substrate/listener/event-handlers_test.go

fix: duplicate and missing message ids

---

app/app.go

fix: use existing message channel for substrate network event handlers

---

.github/workflows/deploy_stage.yml

Remove relayers from devnet pipeline

chore: remove relayers from devnet pipeline

---

cli/cli.go
cli/keygen/cli.go
cli/keygen/generateKey.go
docs/general/CLI.md

Added a CLI command that generates ECDSA keypair and prints it out.

chore: Add keygen CLI

---

tss/resharing/resharing.go
tss/test/communication.go

fix: refresh coordinator being outside the peerstore

---

.github/workflows/deploy_stage.yml

Deploy devnet from bitcoin branch

---

app/app.go

feat: production app

---

.github/workflows/deploy_testnet.yml

Visibility of Image Versions
- Added Tags to update image versions dynamically. 
- Update Actions to latest versions
Related: #[450](https://github.com/sygmaprotocol/devops/issues/450)

chore: visibility of image versions

---

chains/btc/listener/event-handlers_test.go
chains/btc/listener/listener.go
chains/btc/listener/util.go
chains/btc/listener/util_test.go
e2e/btc/btc_test.go
e2e/evm/util.go
example/cfg/config_evm-evm_1.json
example/cfg/config_evm-evm_2.json
example/cfg/config_evm-evm_3.json
example/docker-compose.yml

check for taproot type when calculating amount
check for taproot type when calculating amount

fix: check for taproot type when calculating amount

---

tss/frost/common/base.go
tss/frost/keygen/keygen.go
tss/frost/resharing/resharing.go
tss/frost/signing/signing.go
tss/test/communication.go

fix: add timeout for frost outbound messages

---

chains/evm/listener/eventHandlers/event-handler.go

remove keyshare check
Remove key share check so we can retrigger key reshare and overwrite the current key share in situations where one relayer wasn't able to generate key share

chore: remove keyshare check

---

go.mod
go.sum

Migrate to the new version of `sygma-core` that fixes a problem with processing block range on substrate:
https://github.com/sygmaprotocol/sygma-core/pull/29

fix: update sygma-core version

---

chains/btc/config/config.go
chains/evm/config.go

fix bad non zero check
fix bad non zero check
Closes: https://veridise.notion.site/Bad-non-zero-check-3d60fa66e51643e6884ef981b55b38b5

fix: bad non zero check

---

chains/btc/executor/executor.go

fix possible race condition
Closes: https://veridise.notion.site/Possible-race-conditions-1fd783d2bdab4305bc8d1100e6952fe2

fix: possible race condition

---

app/app.go
chains/evm/listener/eventHandlers/event-handler.go
example/app/app.go
tss/ecdsa/common/utils.go
tss/ecdsa/common/utils_test.go
tss/ecdsa/resharing/resharing.go
tss/ecdsa/resharing/resharing_test.go
tss/frost/resharing/resharing_test.go

Fix removal of ECDSA peers by removing that peer from oldSubset when starting refresh.
Add tests for peer removal.
Add frost reshare to reshare event handler.

fix: remove ECDSA peer

---

chains/btc/executor/executor.go

Execute in Bitcoin executor proposals per resource.
Closes: https://www.notion.so/veridise/Mismatched-resources-20ea8e4c864643b7b8085aadc6c66fcc

fix: enforce proposal execution per resource

---

go.mod
go.sum

fix: bump core to fix panic on invalid domain

---

tss/frost/resharing/resharing.go

fix: update key threshold when doing frost resharing

---

chains/evm/calls/contracts/bridge/bridge.go

This change was accidentally removed during PR merges.
This just brings it back

fix: is proposal executed nonce

---

tss/coordinator.go

fix: treat coordinator missing as a warn log

---

chains/evm/listener/eventHandlers/event-handler.go

fix: remove invalid frost resharing

---

chains/evm/executor/executor.go

fix: add generic call gas limit buffer
