sprintertech/sygma-relayer

app/app.go, ecs/task_definition-0_STAGE.json, ecs/task_definition-1_STAGE.json, ecs/task_definition-2_STAGE.json, ecs/task_definition-3_STAGE.json, ecs/task_definition-4_STAGE.json
For some time our deployment environment was using local network topology, now we are moving to topology that is saved on ChainSafe Storage.
Additionally, fix for missing ENV definition for the topology encryption key inside aws task definition.
=> chore: load topology from Storage

chains/evm/config.go, chains/evm/config_test.go
Set max gas price by default to be 500gwei. It won't be that much as it uses estimate gas price but that is the maximum.
If we want to change on mainnet it is easy to set it in the config.
All the other configurations seem reasonable.
Before it was 20 gwei and tx wouldn't appear on mumbai and goerli when the networks were congested.
Closes: #132
=> fix: increase max gas price allowed by default

config/config.go
Currently, if shared config has extra networks it appends it in its incomplete state. 
This PR only allows for networks that are actually configured in the env or file.
=> fix: ignore extra networks from shared config

.github/workflows/deploy_mainnet.yml
New Features: use Release tags from Testnet to deploy to mainnet.
Expected: Proven Stable version from Testnet environment only should be deployed to mainnet.
This pipeline will not trigger automatically based on commits. It will be a deliberate manual trigger where a stable version image tag will be required as input. Before deployment, this input tag is rendered and substituted in the ecs Task_Definition file. If the input is not provided, the default image tag is 'stable', which will publish the last stable version. keep in mind that Testnet environment published two images with two different tag, v series and stable.
https://app.zenhub.com/workspaces/sygma-protocol-62f126a54b7d5a55203732f0/issues/gh/sygmaprotocol/devops-backlog/48 …
=> feat: mainnet deployment pipeline with release tags

.github/workflows/deploy_testnet.yml
multi-region deployment
Deploy to other regions (us-west-2 and us-east-2)
Simulated the deployment script between 
- region_1 i.e devnet in us-east-2 and
- region_2, i.e testnet in us-west-2
Successful deployment event can be found [here](https://github.com/sygmaprotocol/sygma-relayer/actions/runs/5854645968/job/15870962145)
maintenance
=> chore: multi regional deployment

.github/workflows/deploy_stage.yml
This change is to use the same variable for regions instead of by environment. 
i.e region_1, region_2 instead of devnet_region_1...
Related: #194
=> chore: update aws region

.github/workflows/deploy_mainnet.yml
mainnet Pipeline for deploying to region_3
To ensure the pipeline deploys as expected
I disabled the pipeline for relayer-0 and relayer-1 so that they don't redeploy while I deploy relayer-2
=> chore: testing regional deployment

config/config_test.go, config/relayer/config.go, tss/coordinator.go
The bully process can finish without all the relayers being in it and the next process then starts with invalid coordinators on some relayers because of it.
Increase bully wait time to possibly include more relayers and fix the process coordinator so messages from invalid coordinators cannot break the proccess.
Closes: #226
=> fix: invalid bully restart

.github/workflows/deploy_mainnet.yml, .github/workflows/deploy_stage.yml, .github/workflows/deploy_testnet.yml
Pipeline Status Notification to be delivered to Slack Channel
Modified Github Actions pipeline to send the status to a slack channel. Thus remind the user if the deployment or CI i.e build image failed or successful. 
Related: #300
See the attachment ![Screenshot 2024-01-30 at 11 55 48 PM](https://github.com/sygmaprotocol/sygma-relayer/assets/58168886/d40e4a5d-f7cd-4c30-a179-91647048e285)
=> chore: slack notify

.github/workflows/deploy_mainnet.yml, .github/workflows/deploy_stage.yml, .github/workflows/deploy_testnet.yml
Workflow renaming 
Changing the workflow names to display as follows
- Sygma Devnet
- Sygma Tesntet
- Sygma Mainnet
instead of displaying as Sygma/Deploy/stage
With this change, it will be easy to recognise the pipeline. e.g as Sygm Devnet from `sygma-notifs` slack channel  instead of Sygma/Deploy/stage
Related: #300
=> chore: workflow  renaming

.github/workflows/deploy_mainnet.yml, .github/workflows/deploy_stage.yml, .github/workflows/deploy_testnet.yml
This is to reduce round trip time on the deployment pipeline. Checking out the sygma-relayer repo at deployment is small time-consuming, though negligible, but it is not needed. 
- [x ] New feature (non-breaking change which adds functionality)
=> chore: reduce turnaround time

chains/evm/executor/executor.go, chains/evm/executor/message-handler.go, chains/evm/executor/message-handler_test.go, chains/evm/listener/depositHandlers/deposit-handler.go, chains/evm/listener/depositHandlers/erc1155.go, chains/evm/listener/depositHandlers/erc1155_test.go, chains/evm/listener/depositHandlers/erc20.go, chains/evm/listener/depositHandlers/erc20_test.go, chains/evm/listener/depositHandlers/erc721.go, chains/evm/listener/depositHandlers/erc721_test.go, chains/evm/listener/depositHandlers/generic.go, chains/evm/listener/depositHandlers/generic_test.go, chains/evm/listener/depositHandlers/permissionless.go, chains/evm/listener/depositHandlers/permissionless_test.go, chains/evm/listener/eventHandlers/event-handler.go, chains/evm/listener/eventHandlers/event-handler_test.go, chains/evm/listener/eventHandlers/mock/listener.go, chains/substrate/executor/executor.go, chains/substrate/executor/message-handler.go, chains/substrate/listener/deposit-handler.go, chains/substrate/listener/deposit-handler_test.go, chains/substrate/listener/event-handlers.go, chains/substrate/listener/event-handlers_test.go, chains/substrate/listener/mock/handlers.go, go.mod, go.sum, relayer/transfer/transfer.go
=> feat: add message id to logs

tss/frost/common/base.go
Msg.To when is empty and it is not a broadcast is an error message which should be propagated to all.
Closes: https://www.notion.so/veridise/Incorrectly-handling-empty-msg-To-5be517d2eead4994bbdfdb6206ab2078
=> fix: handle msg.To being empty properly

chains/btc/listener/event-handlers.go, chains/btc/listener/event-handlers_test.go
reduce tx nonce collision chances
Update the CalculateNonce function algorithm to generate a uint64 nonce by concatenating the string representations of a given block number and transaction hash, hashing the concatenated string using SHA-256, and folding the hash into a uint64 value through XOR operations.
Closes: https://veridise.notion.site/Possible-transaction-nonce-collision-ddbb77e582464199accd02c171bd5ed6
=> fix: reduce tx nonce collision chances

docs/general/Arhitecture.md, docs/general/BTC-Deposit-Format.md, docs/general/Deposit.md
add btc deposit format explanation
Closes: https://veridise.notion.site/Unclear-BTC-transaction-assumptions-6b182f76f4c14f9ea967a83e97e532df
=> chore: add btc deposit format explanation

chains/btc/executor/executor.go
Calculate btc inputs with fee estimate when the assumption is the transaction will have at least
as many inputs as outputs.
Closes: https://www.notion.so/veridise/Transactions-blocked-for-low-fees-97816122a11a4604b980fe38cbc5b19e
=> fix: add fee estimate when calculating btc inputs

chains/btc/mempool/mempool.go, chains/btc/mempool/mempool_test.go, chains/btc/mempool/test-data/successful-utxo.json
Sort utxos by oldest to mitigate issues when multiple relayers call the mempool at the same time and get different reuslts.
Closes: https://veridise.notion.site/Dropped-mismatched-messages-122d4c72ddcb4460be658d28115a23e1
=> fix: sort utxos by oldest to prevent mismatched messages

app/app.go, chains/btc/executor/executor.go, chains/evm/listener/eventHandlers/event-handler.go, chains/evm/listener/eventHandlers/event-handler_test.go, chains/evm/listener/eventHandlers/mock/listener.go, example/app/app.go, go.mod, go.sum
Store btc proposals as executed if transaction sent. 
Unlock proposals when doing retry to release pending transactions. 
Retry can be only called by admin and should only be done when sure that the process that failed
has finished.
Retry mechanism will be soon be revisited and implemented so it is called from a single chain and per depositNonce to make it more granular and flexible.
Closes: https://www.notion.so/veridise/Unexecuted-proposals-may-be-lost-ddbd27a7e7a34bbd881469e1532d82d5
=> feat: unlock pending btc proposals when doing retry

chains/evm/listener/eventHandlers/event-handler.go
=> fix: ignore refresh errors to prevent infinite loops

chains/btc/executor/executor.go, tss/frost/signing/signing.go, tss/frost/signing/signing_test.go
*big.Int that ECDSA uses to pass messages removes leading zeroes which then construes a different hash than the Bitcoin node expects.
This changes everything to use []byte directly.
Closes: #340
=> fix: schnorr signature hash missing leading zeroes

.github/workflows/e2e.yml, tss/frost/resharing/resharing.go
Store verificationShares on the new relayer
Closes: #345
=> fix: frost key resharing

app/app.go, chains/substrate/pallet/pallet.go, example/app/app.go, go.mod, go.sum
This PR is adding multiple GSRPC lib version support
=> feat: Multiple GSRPC version support

chains/btc/executor/executor.go, tss/frost/signing/signing.go
Return error when upload to ipfs fails
return error when upload to ipfs fails
=> fix: return error when upload to ipfs fails

comm/p2p/host.go, comm/p2p/host_test.go
Possibly fixes the bug where in peerstore after refresh there are extra peers.
=> fix: remove peer as well as addresses from peerstore

app/app.go, config/config.go, config/config_test.go, example/app/app.go
Match configs by domainID to prevent errors when the shared config and relayer config are mismatched. 
How it functions now:
- relayer config is the source of truth
- SYG_CHAINS from relayer is matched by domainID with the shared config ID
- if the config in shared config is missing the relayer will throw an error
- configs don't have to be ordered 
Closes: #374
=> feat: match configs by domainID

chains/evm/calls/events/events.go, chains/evm/calls/events/listener.go
=> fix: v1 retry signature

.github/workflows/deploy_mainnet.yml, .github/workflows/deploy_testnet.yml, example/docker-compose.yml
Updated the GitHub name to sprinter API
Related: #[issues 588](https://github.com/sprintertech/devops/issues/588#issue-2784021910)
=> chore: relayer - update organisation name to sprinter
